### ISSUE TITLE
Use Transifex for continuous translation please

### ISSUE THREAD

**Issue by p-bo** [jgraph/drawio-nextcloud#1]
Hello,
would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

For instance:

- much more translators will get involved, because without it, they will newer even know about possibility to translate this app - example of benefits for project known in this manner for community of Nextcloud translators (app with recently added to this workflow, based on same request as this one): https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c (se this and ongoing Nextcloud bot commits - translation of app is getting completed/improved in no time)
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)

To conclude: with continuous translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

Thanks :-)

**Comment by p-bo** [comment]
Don't worry, it shouldn't take you much time - just open issue on https://github.com/nextcloud/docker-ci/issues/new/choose (choose Request translations). And you will get checklist as for example this: https://github.com/nextcloud/docker-ci/issues/426 and you can ask [rakekniven](https://github.com/rakekniven) if something is unclear to you.

**Comment by comradekingu** [comment]
It shouldn't take a lot of time, but it does, because TX is an absolute madhouse.
Use https://hosted.weblate.org/hosting/ instead.

**Comment by m-mohamedin** [comment]
@p-bo I've registered the app in Transifex but on first sync, many languages are removed while others are almost emptied. What goes wrong?

**Comment by p-bo** [comment]
@m-mohamedin in that case just ask for import of pre-existing translations as in case of https://github.com/nextcloud/docker-ci/issues/471

**Comment by m-mohamedin** [comment]
Thanks @p-bo,  Transifex is translating faster than the efforts needed to import existing translation (which is incomplete after the latest changes).
I'll close it as the process now is complete
Thanks for the suggestion

**Comment by p-bo** [comment]
Glad to help and thanks @m-mohamedin for implementing this :-)

**Comment by arnowelzel** [comment]
How can one contribute to Transifex translations? I did not find Draw.io for Nextcloud there.

**Comment by p-bo** [comment]
@arnowelzel 
> How can one contribute to Transifex translations? I did not find Draw.io for Nextcloud there.

Hello, there: https://app.transifex.com/nextcloud/nextcloud/translate/#resource/drawio
