### ISSUE TITLE
With Drawio 2.0.0 files can not be saved

### ISSUE THREAD

**Issue by arnowelzel** [jgraph/drawio-nextcloud#13]
Starting with Drawio 2.0.0 it is no longer possible to save files. Neither the "Save" button nor the File - Save menu or keyboard shortcut Strg+S do anything. However if there are changes, the app will report unsaved changes.

I also tried to remove and reinstall the app - that did not help either.

Only downgrading manually to version 1.0.5 fixed that issue.

Server: Nextcloud 25.0.2, diagrams.net 20.8.0

**Comment by davidjgraph** [comment]
What is the environment? Any errors on console, or server logs?

**Comment by m-mohamedin** [comment]
Is this self-hosted draw.io or using the online version?

**Comment by arnowelzel** [comment]
No errors in the console. It just seems to ignore the save request completely. Export as SVG etc. works.

Draw.io is self hosted in a Docker container. The same version works ok with Draw.io 1.0.5.

**Comment by arnowelzel** [comment]
In addition: I run the Docker container (https://github.com/jgraph/docker-drawio) behind a reverse proxy which only forwards HTTP. In did not find anything in the documentation about the use of websockets - may this be a problem?

**Comment by arnowelzel** [comment]
Ok, I found the problem:

When enabling "offline mode", saving is not possible any longer. If that mode is not supported any more, it should be removed from the app settings and the mode should be changed internally during an upgrade of the app.

**Comment by arnowelzel** [comment]
I can confirm that it works now with offline mode enabled as well. Thanks for the quick fix and your good work!
