### ISSUE TITLE
Additional settings cannot be opened

### ISSUE THREAD

**Issue by kleener** [jgraph/drawio-nextcloud#15]
Since version 2.0.1 I cannot open the additional admin settings of Drawio.
Version: 8.1.2
Error message:

[index] Fehler: Exception: Call to undefined method OCA\Drawio\AppConfig::GetDarkMode() in file '/var/www/nextcloud/apps/drawio/lib/Controller/SettingsController.php' line 67 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

I would also like drawio to have its own settings page, then you can find the settings faster and it looks better.

**Comment by m-mohamedin** [comment]
New section added in v2.0.2 but I cannot reproduce the error. Please try the new version and see if it works
Thanks for the report

**Comment by kleener** [comment]
Ok, now it works. Maybe it was also a cache problem with me.
Thanks for the new section :-)
