### ISSUE TITLE
Language selector should be drop-down

### ISSUE THREAD

**Issue by urbalazs** [jgraph/drawio-nextcloud#17]
The Language field is a text field but it should be a drop-down field with the possible languages.

The current field has placeholder text explaining how to set the language but this placeholder text is not visible because "auto" is selected by default. The user cannot know in which format should be the language provided.

Please change this field to a drop-down field with the possible languages. It would be great that the list can contain the ISO code of the language as key and its localized name as value like:

```html
<select name="lang" id="lang">
  <option value="auto">Auto</option>
  <option value="en">English</option>
  <option value="de">Deutsch</option>
  <option value="hu">Magyar</option>
  ...
</select>
```

**Comment by m-mohamedin** [comment]
Will be added in the next release
