### ISSUE TITLE
Collaborate in real time

### ISSUE THREAD

**Issue by matbgn** [jgraph/drawio-nextcloud#2]
Would it be possible to integrate the real time collaborative editing introduced in version 17.0.0?
https://github.com/jgraph/drawio/blob/dev/ChangeLog

Similar to what is described here:
https://www.diagrams.net/blog/real-time-collaboration-diagrams-md

NB: This is a copy from @brtptrs's post on https://github.com/pawelrojek/nextcloud-drawio/issues/183 for the new drawio-nextcloud maintainers

**Comment by aov-arnold** [comment]
Would be a great feature and more powerful than the whiteboard integration app.

**Comment by arnowelzel** [comment]
JFTR: The link describing this is now here:

https://www.diagrams.net/blog/real-time-collaboration-diagrams

**Comment by m-mohamedin** [comment]
Will be added in the next release
