### ISSUE TITLE
FileDeleteListener causing log entry on EVERY file delete

### ISSUE THREAD

**Issue by alx-tuilmenau** [jgraph/drawio-nextcloud#23]
Hello,

after the update to 2.0.2 the FileDeleteListener causes a log entry on EVERY file deletion. All files without a drawio preview will cause an FileNotFoundException, deleted previews will log an error (why - it was succesful?).
Please fix this, maybe this way:

```
try
   {
            $prevFolder = $this->appData->getFolder('previews');
            if ($prevFolder->fileExists($node->getId() . '.png')) { 
                        $prevFolder->getFile($node->getId() . '.png')->delete();
            }
    }
catch (\Exception $e)
```

**Comment by m-mohamedin** [comment]
Thanks for the report. We'll add your fix in the next version
