### ISSUE TITLE
draw.io Nextcloud App

### ISSUE THREAD

**Issue by TwoBe3rs** [jgraph/drawio-nextcloud#25]
Good morning,

I am currently using an NC 25.0.2 with PHP 7.4.33. In addition, version 2.0.2 of draw.io is installed. Recently we have the problem that draw.io files can no longer be opened and created. In the Nextcloud logs I could find the following message: “Could not resolve versionManager! Class version manager does not exist”

Have already done a maintenance:repair, maintenance:access and a db:add-missing-indices and db:add-missing-columns. Unfortunately in vain.

I haven't been able to find anything online about the error message.

Regards

**Comment by jawahiko** [comment]
Hello.
I am currently running
NextCloud 25.0.2
Drawio 2.0.2

When I create a new Drawio file and try to edit it, I get an InternalServerError.
I have checked the logs.
```
Class versionManager does not exist
Could not resolve OCA\\Files_Versions\\\Versions\\IVersionManager! Class OCA\Files_Versions\\IVersionManager does not exist
The message said "OCA\\Files_Versions\\IVersionManager does not exist.
```

I enabled (Versions 1.18.0) plugin and now Drawio is available, but I do not want to enable this plugin as it wastes server space.

I think I used to be able to use Drawio with this Versions plugin disabled, but is the Drawio plugin dependent on the Versions plugin?
Is there a workaround?

Thank you in advance for any help you can give me.

**Comment by TwoBe3rs** [comment]
> The IVersionManager class is in NextCloud since v15
> 
> Do you have special settings like disabling file versions?

No, we have no special settings :/

**Comment by m-mohamedin** [comment]
Thanks @jawahiko for the helpful comment. We managed to reproduce and fix the issue
Thanks @TwoBe3rs for the report.

Fix will be in the next release. You can enable Versions plugin/app as a workaround currently
