### ISSUE TITLE
Realtime Collaboration - Malformed UTF-8 Data

### ISSUE THREAD

**Issue by LukasKlepper** [jgraph/drawio-nextcloud#27]
Hi, after I've initially tested the draw io plugin (it worked very nicely on our previous test-instance) it now throws errors while mouse movement is received.

So currently if user 1 moves his mouse the request gets sent to user 2, but it throws an error in console which says that it was malformed UTF-8 data. Vice versa.

```
P2PCollab.processMsg Error: Malformed UTF-8 data
    stringify https://embed.diagrams.net/js/app.min.js:14
    toString https://embed.diagrams.net/js/app.min.js:12
    stringToObject https://embed.diagrams.net/js/app.min.js:12235
    v https://embed.diagrams.net/js/app.min.js:13199
    joinFile https://embed.diagrams.net/js/app.min.js:13209
    bind https://embed.diagrams.net/js/app.min.js:181
```

I already tried restarting all of the nextcloud containers, didn't help.

What could cause this? As we've not changed the infrastructure it shouldn't be a problem.
We are behind a apache reverse proxy with websocket support enabled.

**Comment by alderg** [comment]
We'll add the received message to the console output for debugging.

**Comment by LukasKlepper** [comment]
Is there any thing I can currently do against it? We would like to use it to collaborate with customers and our team.

**Comment by alderg** [comment]
If you visit https://embed.diagrams.net/clear.html and look at the console again there should be the message that caused this. Could you share that? It would help us to debug this.

**Comment by LukasKlepper** [comment]
Hi the console at https://embed.diagrams.net/clear.html isn't showing anything. 
On NextCloud it still says Malformed UTF-8 data.

It may be interesting that im currently on Firefox 108.0.2 (64-Bit) while NextCloud is on 25.0.2 and Draw.IO Integration on 2.0.2.

**Comment by alderg** [comment]
Try now. Version should be 20.8.9.

**Comment by LukasKlepper** [comment]
@alderg Now the error seems to have additional informations.

```
Error: Malformed UTF-8 data
    stringify https://embed.diagrams.net/js/app.min.js:14
    toString https://embed.diagrams.net/js/app.min.js:12
    stringToObject https://embed.diagrams.net/js/app.min.js:12235
    v https://embed.diagrams.net/js/app.min.js:13199
    joinFile https://embed.diagrams.net/js/app.min.js:13209
 
Object { bytes: "U2FsdGVkX18V4n7YV+8LmTGbLYAsrS6VIZYooPBvrORtCny3M5wlqsVJDAaMciAito0Nc6W88tuw2uIYg10ehPUDvfXjhrYC3bgbGCCAfycdjALUhkp1xRs+PPlkPXYKeCuje1BBleIaADP+8/T/RKBx7cTYZ6gPE+f4Y9cKOOln0TOCVzDLRe273R8jtmdMKJwj7a9U9G0dbcdcsCxwFUco5jbepHS7m0CL7HHmRX3qN5qly9MEih3g1/LJIoExzG4YEOBG952FagQgP4Fwlk5HLkg0cz/CSYYARaZWT9/v4mS5uxY4+WY5cI6l7QsWxopFOsk1XoPdbYslipnKdoobH40/nPVm9VQ+K3H3ZjsofMkd4KeZTovezvNZmc6X", data: "aes" }
 S0Fg8KhrT4xWlrXW5qbo app.min.js:13201:482

```

Hopefully it helps.

**Comment by LukasKlepper** [comment]
I'll check that next week and drop you an email next week.

**Comment by m-mohamedin** [comment]
> I'll check that next week and drop you an email next week.

Please include getFileInfo results on both sender and receiver (the users sharing the file)
Thanks

**Comment by LukasKlepper** [comment]
@m-mohamedin I sent you an email.

**Comment by m-mohamedin** [comment]
A new version of draw.io is released. Can you please visit https://embed.diagrams.net/clear.html to clear the cache then try again if the error is fixed?
Thanks

**Comment by LukasKlepper** [comment]
Thanks, now it works great on our side!
