### ISSUE TITLE
Customized nextcloud drawio configration

### ISSUE THREAD

**Issue by mkaiser** [jgraph/drawio-nextcloud#33]
Hi, 

first: Great Integration! The concurrent access from multiple users worked directly in the current version, making me very happy! :)

I need some help regarding customized configurations for diagrams.net. I hope this is the right place for my question.

Based on the diagrams.net webpage, I spend some time to create a theme with predefined colors, shape layouts, font etc following this guide https://www.diagrams.net/doc/faq/configure-diagram-editor

The configuration dialogue of the diagrams.net webpage (not nextcloud, yet!) allowed me to generate this [link ](https://app.diagrams.net/?src=about#_CONFIG_vVbLjpswFP0alpWMiXksjR+rqptI07U7eAgpwRFx2pl+fW1mwsWelFTTqHIU6drH95z74EJS1AnGjX5S594y05tx+7jTB31yu0lGE1L73wR66vr+bRfjwQzaG5i5/5MdzXc9nyU426R+zQDb2R7OT1YNjRqbBKPaPPvtgnvcexbniVasTNMVqggQUh2fP7Wj1sMNkjytKRUrJBEgJPmhx6Zrx+50gyWTVMhshSUChCzf+rMz0F6r4RaRJAXP2QpRBIjKo/qDuZUxKWmO6zWKEBBSmFENrY/mqHV/gwnVRemP/8gUAUImq9WFgEy/CfPoG/2LCtp8IodmutY+l+vHUZ/069OycIBx1PVRZ0Y9FBU7KkmUPojxomH5yAYiMPJrvklIvkHVbOI6x2ThtyKsAjAlqUBwWrnLCE5RnrFMzmYwAj5iZKlfs1nIKkdQx01abUoQjnSpmnI2XeocAExU4qXSklAi7qf0fxT2PkpL7tds8lKmBEyKnBRQWjImJORUVnVKi4VSRkvIaZYKIu6otM78ggoSmVdgMiQyDr1WY+4SB9JqVrPNQil3FYBGygVfFOCflfLKL2DDkjIwnbBUyAVYODkA5i5reKFUcE4gLCpzWd1FaTQXpBlsMBa43quHsxu52+n9gZgZGj2cdHPl8oMerX7e2pd5kL5OZudTqkPXvySXAbnqdXLpx/k0pOY7Vz4dQsD774dX1NeusbsZBaejOTvW5sqJV7ziuwjDFk2r3wWto03/8rI705pB9cGFydP+fDiG6CDaD2UwDg8eyb229mXb/QI2dbZmNWvQihDGZ2OO15J3j8r9ZQWOqtXSjAdll7n/CdLT6UXkoTvdtbs3WOU2nYuC/wY=), which works well with the diagrams.net webpage. 

Diagrams.net
Extras --> Configuraton (insert JSON stuff) --> Link ("Verknüpfung")
![image](https://user-images.githubusercontent.com/29856783/214810166-70336cd6-5b7c-49c8-9ce5-504a75101b78.png)

Now, I want to integrate it into my Nextcloud instance (externally hosted) using this settings dialogue, but I cannot make it work. 

![image](https://user-images.githubusercontent.com/29856783/214810315-636a4e16-d21f-4a0a-8df0-ae7396106fd7.png)

Using the provided [link ](https://app.diagrams.net/?src=about#_CONFIG_vVbLjpswFP0alpWMiXksjR+rqptI07U7eAgpwRFx2pl+fW1mwsWelFTTqHIU6drH95z74EJS1AnGjX5S594y05tx+7jTB31yu0lGE1L73wR66vr+bRfjwQzaG5i5/5MdzXc9nyU426R+zQDb2R7OT1YNjRqbBKPaPPvtgnvcexbniVasTNMVqggQUh2fP7Wj1sMNkjytKRUrJBEgJPmhx6Zrx+50gyWTVMhshSUChCzf+rMz0F6r4RaRJAXP2QpRBIjKo/qDuZUxKWmO6zWKEBBSmFENrY/mqHV/gwnVRemP/8gUAUImq9WFgEy/CfPoG/2LCtp8IodmutY+l+vHUZ/069OycIBx1PVRZ0Y9FBU7KkmUPojxomH5yAYiMPJrvklIvkHVbOI6x2ThtyKsAjAlqUBwWrnLCE5RnrFMzmYwAj5iZKlfs1nIKkdQx01abUoQjnSpmnI2XeocAExU4qXSklAi7qf0fxT2PkpL7tds8lKmBEyKnBRQWjImJORUVnVKi4VSRkvIaZYKIu6otM78ggoSmVdgMiQyDr1WY+4SB9JqVrPNQil3FYBGygVfFOCflfLKL2DDkjIwnbBUyAVYODkA5i5reKFUcE4gLCpzWd1FaTQXpBlsMBa43quHsxu52+n9gZgZGj2cdHPl8oMerX7e2pd5kL5OZudTqkPXvySXAbnqdXLpx/k0pOY7Vz4dQsD774dX1NeusbsZBaejOTvW5sqJV7ziuwjDFk2r3wWto03/8rI705pB9cGFydP+fDiG6CDaD2UwDg8eyb229mXb/QI2dbZmNWvQihDGZ2OO15J3j8r9ZQWOqtXSjAdll7n/CdLT6UXkoTvdtbs3WOU2nYuC/wY=) as "Draw.io URL" I get the error message "app.diagrams.net is inaccessible (german: "gesperrt"). app.diagrams.net refused the connection. ERR_BLOCKED_BY_RESPONSE " when opening a draw.io file via my nextcloud instance. 

When I change the link from *app.diagrams.net/* to *embed.diagrams.net/* [(like this),](https://embed.diagrams.net/?src=about#_CONFIG_vVbLjpswFP0alpWMiXksjR+rqptI07U7eAgpwRFx2pl+fW1mwsWelFTTqHIU6drH95z74EJS1AnGjX5S594y05tx+7jTB31yu0lGE1L73wR66vr+bRfjwQzaG5i5/5MdzXc9nyU426R+zQDb2R7OT1YNjRqbBKPaPPvtgnvcexbniVasTNMVqggQUh2fP7Wj1sMNkjytKRUrJBEgJPmhx6Zrx+50gyWTVMhshSUChCzf+rMz0F6r4RaRJAXP2QpRBIjKo/qDuZUxKWmO6zWKEBBSmFENrY/mqHV/gwnVRemP/8gUAUImq9WFgEy/CfPoG/2LCtp8IodmutY+l+vHUZ/069OycIBx1PVRZ0Y9FBU7KkmUPojxomH5yAYiMPJrvklIvkHVbOI6x2ThtyKsAjAlqUBwWrnLCE5RnrFMzmYwAj5iZKlfs1nIKkdQx01abUoQjnSpmnI2XeocAExU4qXSklAi7qf0fxT2PkpL7tds8lKmBEyKnBRQWjImJORUVnVKi4VSRkvIaZYKIu6otM78ggoSmVdgMiQyDr1WY+4SB9JqVrPNQil3FYBGygVfFOCflfLKL2DDkjIwnbBUyAVYODkA5i5reKFUcE4gLCpzWd1FaTQXpBlsMBa43quHsxu52+n9gZgZGj2cdHPl8oMerX7e2pd5kL5OZudTqkPXvySXAbnqdXLpx/k0pOY7Vz4dQsD774dX1NeusbsZBaejOTvW5sqJV7ziuwjDFk2r3wWto03/8rI705pB9cGFydP+fDiG6CDaD2UwDg8eyb229mXb/QI2dbZmNWvQihDGZ2OO15J3j8r9ZQWOqtXSjAdll7n/CdLT6UXkoTvdtbs3WOU2nYuC/wY=) the nextcloud page starts loading the diagrams menu, but never finishes.

I unsucessfully tried some other variants of the string e.g. add some URL parameter "?embed=1" etc. :/

Am I missing something? I still have the feeling that I did not fully understand the concept of the app vs. embedded usage.

**Comment by mkaiser** [comment]
Sorry to 'ping', but are there any updates on this? 

Can you reproduce the issue / is it expected behaviour, etc?

**Comment by m-mohamedin** [comment]
The configuration link won't work. We plan to add a custom configuration section in the app nextcloud config page

**Comment by m-mohamedin** [comment]
Configuration setting is added to v2.1.1

**Comment by mkaiser** [comment]
Thank you very much, it works like a charm!

Also it is very convenient, that I can simply parse the JSON config without the string encoding 

I saw in the commit history, that this feature required many changes - THANK YOU!
