### ISSUE TITLE
language is not set according to user interface

### ISSUE THREAD

**Issue by life-on-mars** [jgraph/drawio-nextcloud#36]
draw.io instances in Nextcloud are always in English and as it is embedded the language globe button to change the language does not appear. 
The language can be set via URL with ?lang=lang_CODE. Again, as this is embedded, it's impossible to do so as a user.

Nextcloud version is 25.0.3
App version is 2.1.0

**Comment by m-mohamedin** [comment]
You can set the language from the app settings in Nextcloud

**Comment by m-mohamedin** [comment]
I've tried the auto language settings and it works, the editor language is changed based on the user personal settings -> Language:

![Screenshot 2023-05-12 at 6 26 41 PM](https://github.com/jgraph/drawio-nextcloud/assets/24944765/76efad5e-ebfd-4e55-b5fd-8c00c3c860d4)
![Screenshot 2023-05-12 at 6 26 25 PM](https://github.com/jgraph/drawio-nextcloud/assets/24944765/2a9020e9-95ac-445f-aea2-cb65fb03bc2c)
![Screenshot 2023-05-12 at 6 26 02 PM](https://github.com/jgraph/drawio-nextcloud/assets/24944765/c25a840f-3f68-45e0-878c-344784f9c79f)

**Comment by findlayfeng** [comment]
This bug only exists with Simplified Chinese environment
The reason is that the language code provided by nextcloud is zh_CN
And drawio uses zh
Now I can only enable it globally Simplified Chinese
Above via Google Translate

**Comment by findlayfeng** [comment]
@m-mohamedin
