### ISSUE TITLE
Error in MacOS / Safari

### ISSUE THREAD

**Issue by spreeni151** [jgraph/drawio-nextcloud#37]
When opening a draw.io diagram in Safari browser on MacOs I receive an error message:

**Error: Class 'OrgChart.Annotations.CanBeNullAttribute' is already defined**

This error makes draw.io diagrams unusable in Nextcloud due to a constantly visible "waiting icon" in the middle of the Safari window. The error only occurs with the option 'Offline mode active?' to 'no'.
Everything works very well with Chrome or Firefox browsers, so this seems to be a Safari related error.
Btw. A BIG thanks for your wonderful work, especially for the whiteboard support :-).
Greetings, Frank
![screenshot-drawio](https://user-images.githubusercontent.com/57463889/221423188-025fb13a-86c3-4e5e-8a08-7812a6b4a741.jpg)

**Comment by spreeni151** [comment]
Just an update: on my iPad I get this error in Chrome browser too. Therefore, unfortunately, Nextcloud Draw.io whiteboard cannot be used as a collaborative whiteboard on iPads. Any idea how to fix this or work around?
Kind Regards, Frank

**Comment by a3linux** [comment]
Same error here, 
try to uninstall and re-install draw.io Nextcloud app.  
Nextcloud version is 25.0.4

Client OS is macOS latest version with Safari browser.

**Comment by a3linux** [comment]
As follow the question, I just tried my Nextcloud with Microsoft Edge on the same macOS system, 
draw.io can create new file and edit without above error. 

Will try to get other browser and post updating here.

**Comment by harryhaller58** [comment]
Same error here with safari on an IPad and an IPhone.

**Comment by JohnEridium** [comment]
+1 for this issue 

![image](https://user-images.githubusercontent.com/40388847/226169776-7aac51e2-6840-4007-8fa4-f8142a2582a3.jpeg)

**Comment by davidjgraph** [comment]
Seven reports and nobody has yet posted exact environment details...

**Comment by spreeni151** [comment]
Oh come on, is this the reason why we get no feedback?
Nextcloud 25.0.4
Draw.io App latest version
MacOS latest, iOS latest, Safari latest
I think the issue is easy to reproduce on any Safari browser or every other iOS browser.  As I wrote above: The error only occurs with the option 'Offline mode active?' to 'no'.

**Comment by JohnEridium** [comment]
ah yeah sorry, here's mine (I encountered the error while underway and just found this thread here):
also: it only happens on iOS Safari, in macOS I don't encounter the error. macOS Safari is Version 16.2 (18614.3.7.1.5)

NC version: 25.0.4
draw.io version: 2.1.0

PHP 8.1.14 (cli) (built: Jan 13 2023 10:43:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.14, Copyright (c), by Zend Technologies

ii  apache2                           2.4.41-4ubuntu3.14                           amd64        Apache HTTP Server
ii  apache2-bin                       2.4.41-4ubuntu3.14                           amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                      2.4.41-4ubuntu3.14                           all          Apache HTTP Server (common files)
ii  apache2-utils                     2.4.41-4ubuntu3.14                           amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-php7.4             1:7.4.33-3+ubuntu20.04.1+deb.sury.org+1      amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libapache2-mod-php8.1             8.1.14-2+ubuntu20.04.1+deb.sury.org+1        amd64        server-side, HTML-embedded scripting language (Apache 2 module)

Ubuntu: 20.04.5 LTS

kernel: 5.15.85-1-pve (LXC container)

iOS Safari 16.3.1


is there anything else you need info-wise?

**Comment by davidjgraph** [comment]
> Oh come on, is this the reason why we get no feedback?

Yes, it absolutely is. We're not wasting time trying to work out the correct environment.

Thanks @JohnEridium for being constructive.

**Comment by m-mohamedin** [comment]
Fixed in draw.io v21.1.6
