### ISSUE TITLE
OCP\Files\NotFoundException: /appdata_oc3ll8sjw6bz/drawio/previews

### ISSUE THREAD

**Issue by cetcondor** [jgraph/drawio-nextcloud#40]
Whenever a person deletes a file – unrelated to Draw, e.g. a .docx or .xlsx  –, we get a log entry that Drawio fails: 

[drawio] Fehler: OCP\Files\NotFoundException: /appdata_oc3ll8sjw6bz/drawio/previews at <<closure>>

To me it looks exactly like issue #24 , which is supposed to be closed already.

We use NC 25.0.4, Draw.io app 2.1.0 and PHP 8.0.28

(PS: Thank you for your work!)

**Comment by m-mohamedin** [comment]
The fix is not released yet as it is not urgent (only log noise)
