### ISSUE TITLE
How to display the .drawio file in HTML

### ISSUE THREAD

**Issue by markNZed** [jgraph/drawio-nextcloud#44]
Hi, I would like to use this plugin to edit .drawio files on a NextCloud server and then I want to display those files in an HTML page without converting to PNG or SCG. Is there are simple way to embed the .drawio in HTML ? I looked quite a lot but have not found anything. The NextCloud drawio plugin is working great!

**Comment by m-mohamedin** [comment]
You can try File -> Embed -> HTML

**Comment by markNZed** [comment]
That gives me an embedded version of the .drawio file. If I change the .drawio file it would not update. I'm looking to treat the .drawio file like an img resource (it would require a little bit of Javascript I assume to make that happen)

**Comment by m-mohamedin** [comment]
You can use the iframe method in this page https://www.diagrams.net/doc/faq/embed-html but you'll need a URL that grant access to the diagram to everyone

**Comment by markNZed** [comment]
Unfortunately that option does not exist anymore. I did eventually figure out a way to do it and posted an example at https://github.com/jgraph/drawio/discussions/3430 So I will close this, thank for trying to help too!
