### ISSUE TITLE
Why can't real time collaboration work on self-hosted instance?

### ISSUE THREAD

**Issue by Normand-Nadon** [jgraph/drawio-nextcloud#45]
It is written in the doc that it won't work, but nowhere I could find WHY...

Can someone point me to documentation on the subject? I would really like to self-host my Draw.io instance alongside my Nextcloud Instance

**Comment by Normand-Nadon** [comment]
Is this setup documented somewhere...
We are having issues with collaboration on draw.io lately (things that pop in and out of existence, corrupted files, etc.

I wanted to take the load off diagrams server and put it on our infrastructure to alleviate the problem

**Comment by davidjgraph** [comment]
No, it's not documented. There is no load issue, we don't run a "server", we use cloudflare workers which scale exactly to demand.

**Comment by Normand-Nadon** [comment]
Do you have reports of other users having issues with collaborative work?
We lost huge amount of work lately because of syncing issues!

As soon as we collaborate on a file, we feel like we are playing Russian roulette! Sometimes it goes well, sometime the file gets all messed-up..

**Comment by davidjgraph** [comment]
We've no reports. If you can provide full details as a bug report we can investigate.
