### ISSUE TITLE
Call to undefined method OCA\\Drawio\\AppConfig::GetDrawioConfig()

### ISSUE THREAD

**Issue by burner-** [jgraph/drawio-nextcloud#49]
After upgrading this app it wont start any more and to log I got following error. 
"method":"GET","url":"/apps/drawio/edit?fileId=1834880&isWB=false","message":"Call to undefined method OCA\\Drawio\\AppConfig::GetDrawioConfig() in file '/var/www/nextcloud/apps/drawio/lib/Controller/EditorController.php' line 645"

**Comment by davidjgraph** [comment]
What are your environment details?

**Comment by burner-** [comment]
Server configuration detail

Operating system: Linux 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64

Webserver: Apache/2.4.41 (Ubuntu) (fpm-fcgi)

Database: pgsql PostgreSQL 10.19 (Ubuntu 10.19-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

PHP version: 7.4.3-4ubuntu2.18

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 25.0.5 - 25.0.5.1

User-backends:

OC\User\Database


<details><summary>List of activated apps</summary>

Enabled:
 - activity: 2.17.0
 - admin_audit: 1.15.0
 - calendar: 4.3.2
 - circles: 25.0.0
 - cloud_federation_api: 1.8.0
 - comments: 1.15.0
 - contacts: 5.2.0
 - contactsinteraction: 1.6.0
 - dashboard: 7.5.0
 - dav: 1.24.0
 - drawio: 2.1.1
 - federatedfilesharing: 1.15.0
 - federation: 1.15.0
 - files: 1.20.1
 - files_pdfviewer: 2.6.0
 - files_rightclick: 1.4.0
 - files_sharing: 1.17.0
 - files_trashbin: 1.15.0
 - files_versions: 1.18.0
 - firstrunwizard: 2.14.0
 - logreader: 2.10.0
 - lookup_server_connector: 1.13.0
 - nextcloud_announcements: 1.14.0
 - notifications: 2.13.1
 - oauth2: 1.13.0
 - password_policy: 1.15.0
 - photos: 2.0.1
 - privacy: 1.9.0
 - provisioning_api: 1.15.0
 - recommendations: 1.4.0
 - related_resources: 1.0.4
 - richdocuments: 7.1.3
 - serverinfo: 1.15.0
 - settings: 1.7.0
 - sharebymail: 1.15.0
 - support: 1.8.0
 - survey_client: 1.13.0
 - systemtags: 1.15.0
 - text: 3.6.0
 - theming: 2.0.1
 - twofactor_backupcodes: 1.14.0
 - updatenotification: 1.15.0
 - user_status: 1.5.0
 - viewer: 1.9.0
 - weather_status: 1.5.0
 - workflowengine: 2.7.0
Disabled:
 - bruteforcesettings
 - encryption
 - files_external
 - gallery: 18.5.0
 - suspicious_login
 - twofactor_totp
 - user_ldap


</details>

**Comment by burner-** [comment]
any ideas how to workaround this?

**Comment by m-mohamedin** [comment]
Sometimes the PHP is cached and needs to reset its cache

**Comment by burner-** [comment]
Thank you. I always forgot that this fpm cache can shoot to leg at so many levels. service php7.4-fpm restart fixed this issue.
