### ISSUE TITLE
Menu items drawio and NC office are both „Diagram“

### ISSUE THREAD

**Issue by aov-arnold** [jgraph/drawio-nextcloud#5]
Both „new file“ menu items are „Diagram“ and only differ in the icon.
- Either the drawio menu item should be called for example „Drawing“ to be able to tell which is which
- or there should be an option to replace the „Diagram“ item from NC office  with the drawio one if that’s technically possible
- or the drawio item name should be configurable: some use drawio as whiteboard with sketch theme (especially when #2 is implemented) and some as drawing app with e.g. kennedy theme

**Comment by KamistixX** [comment]
Same opinion. I think draw.io diagram solution is better than Collabora's one, so I would like to hide it in this list.

Is there a way to do it so draw.io remains the only diagram app on a Nextcloud instance?

**Comment by m-mohamedin** [comment]
Hi,

Is this still an issue with the new icons. Unfortunately, we cannot hide other apps items. Also, using a longer name like "New draw.io Diagram" is not necessary in my opinion with the clear new icons?

Real-time collaboration is added as well as a new Whiteboard item

**Comment by aov-arnold** [comment]
@m-mohamedin Hi, in my opinion it is still not ideal that both icons have the same text. Maybe "New drawing" would be an option to make it more clear?

Would it even be possible to make the text configurable via settings? Than you could rename it according to your needs... for example if you use draw.io as whiteboard you change the text to "New whiteboard".

**Comment by rasos** [comment]
Hiding menu items can be done with custom CSS.  I am not using Collabora, so I don't know the exact CSS attribute for `Diagram`, but we do it for the [Link Editor App](https://github.com/te-online/files_linkeditor) hiding the webloc item (which is only relevant for MacOS) like this:

`.menuitem[data-templatename^="Link.webloc"] {display: none !important;}`

**Comment by aov-arnold** [comment]
> Hiding menu items can be done with the [Custom CSS App](https://apps.nextcloud.com/apps/theming_customcss). I am not using Collabora, so I don't know the exact CSS attribute for `Diagram`, but we do it for the [Link Editor App](https://github.com/te-online/files_linkeditor) hiding the webloc item (which is only relevant for MacOS) like this:
> 
> `.menuitem[data-templatename^="Link.webloc"] {display: none !important;}`

@rasos I will try this approach for now. Thank you!

**Comment by aov-arnold** [comment]
@m-mohamedin Where can I vote?

**Comment by m-mohamedin** [comment]
> @m-mohamedin Where can I vote?

Just like this issue
