### ISSUE TITLE
Failed deletion bug persists after update

### ISSUE THREAD

**Issue by Cl00e9ment** [jgraph/drawio-nextcloud#51]
## Bug

The logs are spammed with the following message:

```
OCP\Files\NotFoundException: /appdata_XXXX/drawio/previews
```

## Existing (closed) reports

- #23
- #24
- #40

## The fix apparently did not work

The bug is still happening, supposedly because the fix is not merged yet. See https://github.com/jgraph/drawio-nextcloud/issues/40#issuecomment-1450909894

However, I'm using the latest version (2.1.1), and the fix is present since 2.1.0. See https://github.com/jgraph/drawio-nextcloud/blob/v2.1.0/lib/Listeners/FileDeleteListener.php#L41

**Comment by Cl00e9ment** [comment]
The exception is thrown on [line 39](https://github.com/jgraph/drawio-nextcloud/blob/v2.1.1/lib/Listeners/FileDeleteListener.php#L39), so there should probably be another verification to check that the directory exists. Or directly check for the existence of the file, without creating the directory object.

**Comment by m-mohamedin** [comment]
Thanks for the report.
It will be fixed in the next release

**Comment by lopez-damiano** [comment]
> Thanks for the report. It will be fixed in the next release

Thanks !

**Comment by Cl00e9ment** [comment]
Hi @m-mohamedin, I think that this bug fix alone should justify the publication of a v2.1.2. Logs are spammed by Drawio for months now, and it's a big annoyance, because other errors are lost in the wall of spam.
The amount of reports shows by itself that people are waiting for this bug fix.
Thank you!

**Comment by davidjgraph** [comment]
What reports, there's not a single vote for this issue?

**Comment by Cl00e9ment** [comment]
See the 3 linked issues in the initial comment + the one in the Nextcloud server repo linked above + this one.
This is 5 different bug reports for the same issue.

**Comment by davidjgraph** [comment]
OK, I sort by issue votes, people need to thumbs up issues to get attention.

**Comment by m-mohamedin** [comment]
Released, please give it a try and let us know

**Comment by Cl00e9ment** [comment]
Thank you ! I updated, so far there is no errors in the logs. I'll keep you inform if they appear again.
