### ISSUE TITLE
Allow use of drawio plugins

### ISSUE THREAD

**Issue by geiseri** [jgraph/drawio-nextcloud#56]
I cannot seem to find a way to add [drawio plugins ](https://www.drawio.com/doc/faq/plugins) to my editor.  It would be nice to allow the use of these.  It is unclear though if these are able to be used with [embed](https://embed.diagrams.net) or just https://app.diagrams.net though.  It seems to say that it cannot be supported by Jira/confluence, so maybe it cannot be.  If this is the case you can close the issue as wontfix so its preserved for posterity =)

**Comment by davidjgraph** [comment]
Unfortunately, we'll have to say no to this. Plugins add security reviews on every platform and we simply don't have the resources to extend that to nextcloud.
