### ISSUE TITLE
Can't import .vsdx diagrams

### ISSUE THREAD

**Issue by RicardoPQ-com** [jgraph/drawio-nextcloud#58]
Dear all, I remember I used to import Visio diagrams into draw.io right from my Nextcloud's site, just right clic and import, but now I can't find that option. Is it a missing option or am I missing something?

**Comment by sebastiaanveld** [comment]
Could it be that the extension is now claimed by another App? For me .vsdx is opened in Nextcloud Office (Collabora Office) by default.

**Comment by m-mohamedin** [comment]
I'm not aware of that option, but you can import from draw.io editor:
![Screenshot 2024-01-01 at 6 44 36 PM](https://github.com/jgraph/drawio-nextcloud/assets/24944765/15d71c74-faf6-4ea0-918d-ab49b222a9ff)
