### ISSUE TITLE
Nextcloud 25 support

### ISSUE THREAD

**Issue by sunjam** [jgraph/drawio-nextcloud#6]
Related to https://github.com/pawelrojek/nextcloud-drawio/issues/181

Manual fix
`<nextcloud min-version="11" max-version="25"/>`

**Comment by VVD** [comment]
Where is current upstream: here or pawelrojek/nextcloud-drawio?

**Comment by wizdude** [comment]
you can also just "enable untested app" and so far it appears to be working fine, but it would be nice for someone to go over this and work out if there are any compatibility issues or other problems that need to be resolved.

**Comment by m-mohamedin** [comment]
Done

**Comment by VVD** [comment]
Thanks!
