### ISSUE TITLE
Nextcloud 28 support

### ISSUE THREAD

**Issue by VVD** [jgraph/drawio-nextcloud#63]
Error in logs after update Nextcloud from 27 to 28 and force turn on Draw.io plugin:
```
Error Call to undefined method OC\Server::getEventDispatcher()
Could not boot drawio: Call to undefined method OC\Server::getEventDispatcher()
```
Can't open schema in Draw.io from Nextcloud too.

**Comment by VVD** [comment]
Did changes:
lib/Controller/EditorController.php(606):
```
-        $eventDispatcher = \OC::$server->getEventDispatcher();
+        $eventDispatcher = \OC::$server->get(\OCP\EventDispatcher\IEventDispatcher::class);
```
lib/AppInfo/Application.php(57):
```
-        $eventDispatcher = \OC::$server->getEventDispatcher();
+        $eventDispatcher = \OC::$server->get(\OCP\EventDispatcher\IEventDispatcher::class);
```
appinfo/info.xml(23):
```
-        <nextcloud min-version="20" max-version="27"/>
+        <nextcloud min-version="20" max-version="28"/>
```
Errors in logs disappeared, but the plugin didn't work.

**Comment by JulienSambre** [comment]
Hi!

Same issue here. I had to disable the plugin in order to not having error logs. Waiting for the upgrade of this plugin :).

**Comment by davidjgraph** [comment]
Nextcloud 28 was released on the 12th December, that's 4 days ago. We haven't marked as being compatible with 28, https://apps.nextcloud.com/apps/drawio.

If you want to upgrade on the day of nextcloud release, draw.io isn't going to work. We'll generally update within a month of release, but nextcloud isn't a core integration of ours, people have to find spare time to work on it.

So, you're welcome to point out that there's a new nextcloud and wait for us to update, but ETA will always be in the order of a month.

**Comment by m-mohamedin** [comment]
v3.0.0 is released for Nextcloud 28. Please consider it a beta version and report any issues you may have.
