### ISSUE TITLE
Draw.io 3.0.0 settings contain duplicate elements for German translation

### ISSUE THREAD

**Issue by arnowelzel** [jgraph/drawio-nextcloud#66]
When I open the settings for Draw.io in German informal ("Deutsch (Persönlich: Du)"), the control for "enable diagram previews" is doubled:

![image](https://github.com/jgraph/drawio-nextcloud/assets/6613614/d073fc2c-9d6a-47b5-883d-f7cdb0f42dbc)

The original in English is OK:

![image](https://github.com/jgraph/drawio-nextcloud/assets/6613614/24b63bd3-9b4c-421e-a54e-094035890628)

Also French is OK, it seems, only the German version is affected:

![image](https://github.com/jgraph/drawio-nextcloud/assets/6613614/e547bfe7-1932-4d32-bcf2-d0594327f5f8)

**Comment by arnowelzel** [comment]
The bug is here - `apps/drawio/l10n/de.js`

```
    "Enable libraries?" : "Diagrammvorschau aktivieren?",
    "Enable diagram previews?" : "Diagrammvorschau aktivieren?",
```

This should be:

```
    "Enable libraries?" : "Bibliotheken aktivieren?",
    "Enable diagram previews?" : "Diagrammvorschau aktivieren?",
```

**Comment by arnowelzel** [comment]
Closing as completed.

**Comment by xenothrox** [comment]
I'm using NC version 30.0.4 with **draw.io version 3.0.3** and can recreate the issue mentioned above in the same constellation.

The wrong translation only comes up if "German informal ("Deutsch (Persönlich: Du)")" is active in personal settings.
When "German formal ("Deutsch (Förmlich: Sie)")" is used, everything's correct.

It seems like the same file as mentioned above got contains the bug 

> apps/drawio/l10n/de.js

All other related files 
`de.json`
`de_DE.js`
`de_DE.json`
contain the correct translation.

Would it be possible to re-check this issue?
