### ISSUE TITLE
Dark theme doesn't work 

### ISSUE THREAD

**Issue by tripp528** [jgraph/drawio-nextcloud#7]
As shown, the dark theme does not work. All other themes work as expected. 

<img width="173" alt="Screen Shot 2022-11-10 at 12 43 06 AM" src="https://user-images.githubusercontent.com/33329853/201029796-625e485e-d506-4b9b-975f-d8cd1515c372.png">
<img width="419" alt="Screen Shot 2022-11-10 at 12 43 18 AM" src="https://user-images.githubusercontent.com/33329853/201029810-4b2f4090-92b8-4dbf-b6a5-ff408975de1a.png">

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
