### ISSUE TITLE
Nextcloud Integrity check issue

### ISSUE THREAD

**Issue by servoronine** [jgraph/drawio-nextcloud#70]
Hi, 

I am facing an issue which I believe is related to Draw.io Nextcloud app. I have upgraded to Nextcloud 28 and subsequently Nextcloud 28.0.1. Since then I get an inconsistency error as part of Nextcloud standard check:

![image](https://github.com/jgraph/drawio-nextcloud/assets/44262745/037720ef-cf4c-4c7e-9afd-083488d49ab5)

![image](https://github.com/jgraph/drawio-nextcloud/assets/44262745/e38bc891-25ae-411c-9ab2-5950b1c666ad)

Is this something that needs to be addressed as part of Draw.io app or a core Nextcloud issue? Thanks!

**Comment by koboldMaki** [comment]
Hi,

Today i updated my Nextcloud to 28.0.1 and get the exactly same issue. Are there any helps to clear this? Or why was it closed without any comment?

Thanks

**Comment by siccovansas** [comment]
Same issue in Nextcloud 28.0.4

**Comment by kopierschnitte** [comment]
Same problem in NC 29.0.2

**Comment by BloodyIron** [comment]
Why was this closed? The issue persists on v33.0.2

**Comment by davidjgraph** [comment]
Because there is no way to fix it at our end. Keeping it open suggests it's possible to fix.

**Comment by arnowelzel** [comment]
Writing anything to the core of Nextcloud will always cause problems.

Please have a look at https://docs.nextcloud.com/server/stable/admin_manual/configuration_mimetypes/index.html - this describes how to add a custom MIME type.

**Comment by davidjgraph** [comment]
We've tried that and other routes, the current solution is the only one that "works" without breaking anything more serious than this upgrade route.

**Comment by arnowelzel** [comment]
Ok, weird. I wonder how other applications manage this, which also provide their own MIME types.

**Comment by iasdeoupxe** [comment]
@davidjgraph Maybe submit the files directly to Nextcloud similar to?
- nextcloud/server#45353
- nextcloud/whiteboard#6

unless this had changed:

> Currently there is no API to do that as an app, so it would need to be done in server

Above also explains this how other apps doing it:

> I wonder how other applications manage this, which also provide their own MIME types.

**Comment by iasdeoupxe** [comment]
Understood, in this case archiving this repository might be an option:

https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories
