### ISSUE TITLE
no drawio integration in Nextcloud app for iOS?

### ISSUE THREAD

**Issue by bh11** [jgraph/drawio-nextcloud#71]
Opening .drawio documents in the Nextcloud app for  iOS  appers not to work. Seems that the extension .drawio is not recognised – the Nextcloud app asks for a local app when trying to open .drawio documents. Also, there is no entry for creating .drawio documents (big blue plus button). Drawio works without problems when using the web interface.

Nextcloud office integration in the Nextcloud app for iOS works without problems, it opens all relevant files and allows to create new ones via the + button. 

Not sure if this is a bug or a feature request.

Nextcloud server 28.02
iOS app version 5.0.0
iPadOS 17.3

Thanks for making drawio available within Nextcloud!

**Comment by davidjgraph** [comment]
It's a feature request, but we don't have the resources to look. If someone wants to submit a fully tested PR, that works, but meanwhile in the real world, it won't get done.
