### ISSUE TITLE
Allow Nextcloud Version 30

### ISSUE THREAD

**Issue by beccon4** [jgraph/drawio-nextcloud#83]

**Comment by m-mohamedin** [comment]
Can you please change the version manually and confirm the app works as is with v30?

Change the line 
`<nextcloud min-version="28" max-version="29"/>`
to
`<nextcloud min-version="28" max-version="30"/>`

In the file appinfo/info.xml

Thanks

**Comment by socialize-IT** [comment]
@m-mohamedin : I just checked with nextcloud 30. Could not find any errors. Add new files, safe files and preview generation are working. Did not check collaborative editing.

**Comment by m-mohamedin** [comment]
Thanks for your help
v3.0.3 released with Nextcloud 30 support
