### ISSUE TITLE
Can not pass integrity check

### ISSUE THREAD

**Issue by ITsPro-CN** [jgraph/drawio-nextcloud#84]
The modification in core/js/mimetypelist.js seems to maintain an old hash value.
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
	- EXTRA_FILE
		- core/img/filetypes/dwb.svg
		- core/img/filetypes/drawio.svg

**Comment by m-mohamedin** [comment]
Duplicate of https://github.com/jgraph/drawio-nextcloud/issues/26
