### ISSUE TITLE
Version 1.0.4 can not be installed via the app store

### ISSUE THREAD

**Issue by arnowelzel** [jgraph/drawio-nextcloud#9]
When trying to install version 1.0.4 from the app store I get the following error message:

"An error occurred during the request. Unable to proceed.
Extracted app drawio has more than 1 folder"

Also updating to 1.0.4 fails for the same reason.

**Comment by ant0nwax** [comment]
actually i removed draw.io 1.0.3 in order to test this and now i cannot even find a way how to install draw.io 1.0.3 does someone has a hint on how to do that? Thank you

**Comment by Omaha2002** [comment]
> actually i removed draw.io 1.0.3 in order to test this and now i cannot even find a way how to install draw.io 1.0.3 does someone has a hint on how to do that? Thank you

If linux:
cd /home/user
wget https://github.com/jgraph/drawio-nextcloud/releases/download/v.1.0.4/drawio-v1.0.4.tar.gz
tar -xvf drawio-v1.0.4.tar.gz
cd drawio
rm ._*
cd /var/www/nextcloud/apps
cp -R /home/user/drawio .
cd ..
sudo -u www-data app:enable drawio

**Comment by adil452100** [comment]
Now, the version 1.0.4 from the app store through this error :
Error: App with id drawio has invalid signature

That's because it was updated 5 minutes ago and the package maintainer missed something ?

**Comment by endotom** [comment]
In nc 23 and 24 it's not possible to update the App to 1.04.
The old one (1.03) is working.
Error: not possible to install...

**Comment by m-mohamedin** [comment]
Should be fixed now.
Thanks for the report

**Comment by endotom** [comment]
works !

**Comment by ant0nwax** [comment]
Thank you for this super fast solving, have a great weekend!

**Comment by arnowelzel** [comment]
Thanks for the fast fix! Great job.
